flaskapp/site/routes.py
from flask import render_template, redirect, flash, url_for, request, Blueprint, session, g, current_app
from flaskapp import db
from flaskapp.config import flash_categories
from flaskapp.models import DatabaseManager, User, Day, Profilechange, db_errors
from flaskapp.site.forms import (
    RegistrationBoxForm,
    LoginBoxForm,
    ForgotPasswordForm,
    ChangePasswordForm,
    AdminForm,
    ProfileSettingsForm,
    SecretKeyForm
    )
from functools import wraps


mod = Blueprint('site', __name__)


dm = DatabaseManager(db, User, Day, Profilechange)

def requires_session(func):
    @wraps(func)
    def wrapper(*args, **kwds):
        if not g.email or not g.password:
            return render_template('not_signed_in.html')
        return func(*args, **kwds)
    return wrapper


@mod.before_request
def before_request():
    g.email = None
    g.password = None
    if 'email' in session:
        g.email = session['email']
    if 'password' in session:
        g.password = session['password']


@mod.route('/debug/drop', methods=['GET'])
# testing route!
def debug():
    # drops the data
    if 'email' in session:
        session.pop('email', None)
    if 'password' in session:
        session.pop('password', None)
    db.drop_all()
    db.create_all()
    return render_template('debug.html', message='The database has been cleaned successfully!')

@mod.route('/admins_control', methods=['GET', 'POST'])
def admins_control():
    form = SecretKeyForm()

    if form.validate_on_submit():
        if form.data['control_key'] == current_app.config['ADMINS_CONTROL_KEY']:
            if form.data['isDeletingAdmin']:
                print(f"\n\nDeleting admin {form.data['email']}\n")
                if dm.remove_user(form.data['email']):
                    flash(f"Admin {form.data['email']} has been removed!", flash_categories['success'])
                    return redirect(url_for('site.admins_control'))
                flash(f"There's no account with {form.data['email']} e-mail!", flash_categories['error'])
                return redirect(url_for('site.admins_control'))
            try:
                dm.admin_registration(form.data['email'], form.data['password'])
            except db_errors['USER_ALREADY_EXISTS']:
                flash(f"Looks like user with e-mail {form.data['email']} already exists!", flash_categories['error'])
                return redirect(url_for('site.admins_control'))
            flash(f"New admin {form.data['email']} has been created", flash_categories['success'])
            return redirect(url_for('site.admins_control'))
        flash('Invalid secret key!', flash_categories['error'])
        return redirect(url_for('site.admins_control'))
    return render_template('admins_control.html', form=form)


@mod.route('/', methods=['GET'])
@requires_session
def index():
    return render_template('index.html')


@mod.route('/oups')
def not_signed_in():
    return render_template('not_signed_in.html')


@mod.route('/registration', methods=['GET', 'POST'])
def registration():
    form = RegistrationBoxForm()

    if form.validate_on_submit():
        try:
            dm.user_registration(
                form.data['name'],
                form.data['surname'],
                form.data['email'],
                form.data['password'],
                form.data['room']
                )
            flash('Your registration request has been sent successfully!' +
                'Please wait until administrator accepts your form...', flash_categories['success'])
            return redirect(url_for('site.registration'))
        except db_errors['USER_ALREADY_EXISTS']:
            flash('Sorry, user with such an e-mail already exists. Please, try again', flash_categories['error'])
            return redirect(url_for('site.registration'))
    return render_template('registration.html', form=form)


@mod.route('/sign_in', methods=['GET', 'POST'])
def sign_in():
    form = LoginBoxForm()

    if form.validate_on_submit():
        try:
            if dm.user_sign_in(form.data['email'], form.data['password']):
                session['email'] = form.data['email']
                session['password'] = form.data['password']
                return redirect(url_for('site.index'))
            flash('Incorrect e-mail or password', flash_categories['error'])
            return redirect(url_for('site.sign_in'))
        except (db_errors['USER_REGISTRATION_REJECTED'], db_errors['USER_DOES_NOT_EXIST']):
            flash('Incorrect e-mail or password', flash_categories['error'])
            return redirect(url_for('site.sign_in'))
    return render_template('sign_in.html', form=form)


@mod.route('/change_password')
def change_password():
    form = ForgotPasswordForm()

    if form.validate_on_submit():
        print('Gocha!')
    return render_template('change_password.html', form=form)


@mod.route('/admin')
def admin():
    form = AdminForm()
    if form.validate_on_submit():
        print('Gotcha!')
    return render_template('admin.html', form=form)

flaskapp/templates/admin.html
{% extends "base.html" %}

{% block content %}
<div id="app">
  
  <div v-show="processing_ajax" class="centred-box" style="text-align: center;">
    <h3>[[ ajax_processing_message ]]</h3>
    <div class="spinner-grow" role="status">
        <span class="sr-only">Loading...</span>
      </div>
  </div>
  
  <form v-show="!processing_ajax && show_login_window" class="centred-box" action="{{ url_for('site.sign_in') }}" method="POST">
      {{ form.hidden_tag() }}
      <h1>
        admin login page
      </h1>
      <p>once you sign in, your token will be stored</p>
      <div class="reg-grid">
          <div class="form-group reg-grid-element">
              <label>e-mail</label>
              {{ form.email(ref="admin_email", class="form-control", placeholder="remember your e-mail?") }}
              {% if form.email.errors %}
                  <ul>{% for error in form.email.errors %} <li>{{ error }}}</li> {% endfor %}</ul>
              {% endif %}
          </div>
          <div class="form-group reg-grid-element">
              <label>password</label>
              {{ form.password(ref="admin_password", class="form-control", placeholder="don't forget the password") }}
              {% if form.password.errors %}
                  <ul>{% for error in form.password.errors %} <li>{{ error }}}</li> {% endfor %}</ul>
              {% endif %}
          </div>
      </div>
      <div class="form-group">
              <button class="btn btn-success" @click.prevent="getFormData()">sign in!!</button>
              <button type="button" class="btn btn-danger" onclick="location.href='{{ url_for('site.sign_in') }}';">Oups, I'm not admin</button>
          </div>
          
          {% with messages = get_flashed_messages(with_categories=true) %}
          {% if messages %}
              {% for category, message in messages %}
                  <div class="alert alert-{{ category }}" role="alert">        
                      {{ message }}
                  </div>
              {% endfor %}
              
          {% endif %}
          {% endwith %}
          <transition name="fade">
          <div v-if="server_message" class="alert alert-danger" role="alert">
              [[ server_message ]]
            </div>
          </transition>
  </form>

  <transition name="fade">
  <div v-if="show_sign_out_warning" class="centred-box">
    <h1>Are you sure you want to sign out?</h1>
    <div class="form-group">
      <button type="button" v-on:click="signOut();" class="btn btn-success"> Sure! </button>
      <button type="button" v-on:click="unpressedSignOut();" class="btn btn-danger"> No, I'm not sure about it... </button>
    </div>
  </div>
</transition>

<div class="popup-window" v-if="show_login_window || show_sign_out_warning"></div>
<h1 style="text-align: center;">admin page</h1>
  <div class="card text-center">
      <div class="card-header">
        <ul class="nav nav-tabs card-header-tabs">
          <li class="nav-item">
            <a class="nav-link" v-on:click="getDays();" href="#">days</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" v-on:click="getRegistrations();" href="#">registrations</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" v-on:click="getProfilechanges();" href="#" tabindex="-1" aria-disabled="true">profile changes</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" style="color: red;" v-on:click="pressedSignOut();;" href="#">sign out</a>
          </li>
        </ul>
      </div>
      <div class="card-body">
        
          <!--
              Here is the table
          -->
            



  <table v-if="!show_getAPIInfo_error_message && !processing_link_request" class="table">
      <thead class="thead-dark">
        <tr>
          <th v-for="parameter in link_data.parameters" scope="col">[[ parameter ]]</th>
        </tr>
      </thead>
      <tbody>
        <tr v-for="iterable in link_data.iterable">
          <td v-for="i in iterable" scope="row">[[ i ]]</td>
          <td class="btn-group">
                  <button class="btn btn-outline-success">accept</button>
                  <button class="btn btn-outline-danger">reject</button>
          </td>
        </tr>
        
        
      </tbody>
    </table>
    <transition name="fade">
        <p v-if="show_getAPIInfo_error_message" stype="text-align: center;"> [[ getAPIInfo_error_message ]] </p>
    </transition>
    <div v-if="processing_link_request">
      <h2>Waiting for server response...</h2>
      <div class="spinner-grow" role="status">
        <span class="sr-only">Waiting...</span>
      </div>
    </div>
      </div>
    </div>
</div>
  <script type="module" src="../static/js/admin.js"></script>
  
{% endblock %}

flaskapp/templates/admins_control.html
{% extends "base.html" %}


{% block content %}
<div id="app">
<form class="centred-box" action="{{ url_for('site.admins_control') }}" method="POST">
    {{ form.hidden_tag() }}
    <h1>admins control page (create or delete admins)</h1>
    <div class="reg-grid">
        
            <div class="form-group reg-grid-element">
                    <label>admin's e-mail</label>
                    {{ form.email(class="form-control", placeholder="email here") }}
                    {% if form.email.erros %}
                        <ul>{% for error in form.email.erros %} <li>{{ error }}</li> {% endfor %}</ul>
                    {% endif %}
                    
                </div>
            <div class="form-group reg-grid-element">
                    <label>password</label>
                    {{ form.password(class="form-control", placeholder="This field is only required if you want to create new admin") }}
                    {% if form.password.erros %}
                        <ul>{% for error in form.password.erros %} <li>{{ error }}</li> {% endfor %}</ul>
                    {% endif %}
                    
                </div>
            <div class="form-group reg-grid-element">
                    <label>control key</label>
                    {{ form.control_key(class="form-control", placeholder="enter your secret key") }}
                    {% if form.control_key.erros %}
                        <ul>{% for error in form.control_key.erros %} <li>{{ error }}</li> {% endfor %}</ul>
                    {% endif %}
                    
                </div>
                <div class="form-group reg-grid-element">

                </div>
            <div class="form-group reg-grid-element">
                {{ form.isDeletingAdmin(ref='isDeletingAdmin') }}
            <label class="form-check-label">want to delete the admin?</label>
            </div>
    </div>
    <div class="form-group">
            <button type="submit" ref="main_button" class="btn btn-success">commit</button>
            <button type="button" class="btn btn-primary" onclick="location.href='{{ url_for('site.sign_in') }}';">
                I don't think I'm supposed to be here
            </button>
            <button type="button" class="btn btn-secondary" @click.prevent="adminsShowButton()"> [[ show_admins_button_text ]] </button>
            <div v-if="processing_ajax" class="spinner-grow" role="status">
                <span class="sr-only">Loading...</span>
              </div>
            </div>
            <transition name="fade">
            <div v-if="is_showing_admins_list" v-bind:class="[[ admins_list_style_class ]]" role="alert">
                <h1>admins</h1>
                <hr>
                <li v-for="(email, index) in admins_list">
                    [[ index + 1 ]].     [[ email ]]
                </li>
              </div>
            </transition>
    
        {% with messages = get_flashed_messages(with_categories=true) %}
            {% if messages %}
                {% for category, message in messages %}
                    <div class="alert alert-{{ category }}" role="alert">
                        {{ message }}
                    </div>
                {% endfor %}
            
            {% endif %}
        {% endwith %}
</form>
</div>
<script type="module" src="../static/js/admins_control.js"></script>
{% endblock %}

flaskapp/templates/base.html
{% block head %}
    <link href="https://bootswatch.com/4/slate/bootstrap.min.css" rel="stylesheet" type="text/css">
    <link href="../static/css/style.css" rel="stylesheet" type="text/css">
{% endblock %}

{% block sidebar %}
{% endblock %}

{% block content %}
{% endblock %}

flaskapp/templates/change_password.html
{% extends "base.html" %}
{% block title %}
    forgot password
{% endblock %}

{% block content %}
<form class="centred-box" action="{{ url_for('site.registration') }}" method="POST">
    <div class="reg-grid">
        <div class="form-group reg-grid-element">
            <label>We'll send you a new password! You'll be able to change it then!</label>
            {{ form.email(class="form-control", placeholder="your e-mail here, make sure it's used in our database") }}
        </div>
    </div>
    <div class="form-group">
            <button type="submit" class="btn btn-success">send new password</button>
            <button type="button" class="btn btn-primary" onclick="location.href='{{ url_for('site.registration') }}';">registration</button>
            <button type="button" class="btn btn-primary" onclick="location.href='{{ url_for('site.sign_in') }}';">sign in</button>
        </div>
    
</form>
{% endblock %}

flaskapp/templates/debug.html
{% extends "base.html" %}

{% block content %}

    {% if message %}
        <h1>{{ message }}</h1>
    {% endif %}
{% endblock %}

flaskapp/templates/index.html
{% extends "base.html" %}
{% block title %}
    main
{% endblock %}

{% block sidebar %}
<div id="app">
    
            <ul class="nav fixed-pos nav-pills navigation-bar flex-column" id="ui">
                <li>
                    <h3>name surname</h3>
                    <h4>room</h4>
                </li>
                <li class="nav-item">
                    <button class="nav-link navigation-btn btn-block" v-on:click="show = !show">edit profile</button>
                </li>
                <li class="nav-item">
                        <button class="nav-link navigation-btn btn-danger btn-block" id="logoutButton" data-toggle="modal" data-target="#logoutWindow">log out</button>
                </li>
            
                <transition name="fade">
                    <li v-if="show" class="profile-settings" id="settings-box">
                            <h3>settings...</h3>
                            <br>
                            <label>new name</label>
                            <input type="text" class="form-control" placeholder="new name here...">
                            
                            <label>new surname</label>
                            <input type="text" class="form-control" placeholder="new surname here...">
                            
                            <label>new room</label>
                            <input type="text" class="form-control" placeholder="new room here...">
                            
                            <div class="btn-group profile-el">
                                <button type="button" class="btn btn-outline-success">commit changes</button>
                                <button type="button" class="btn btn-outline-danger">cancel changes</button>
                            </div>
                    
                            <div class="btn-group profile-el">
                                <button type="button" class="btn btn-primary">change e-mail</button>
                                <button type="button" class="btn btn-primary">change password</button>
                            </div>
                        </li>
                </transition>
            
            </ul>

</div>
{% endblock %}

{% block content %}
<div class="main-content" id="calendar">
    <button class="btn btn-primary btn-lg btn-block">previous month</button>
    <div class="weekdays">
        <h1>mon.</h1>
        <h1>tue.</h1>
        <h1>wed.</h1>
        <h1>thu.</h1>
        <h1>fri.</h1>
        <h1>sat.</h1>
        <h1>sun.</h1>
    </div>
    <div class="calendar">


        <div class="card text-white bg-dark mb-3">
                <div class="card-header">-</div>
                <div class="card-body card-info">
                </div>
            </div>

        <div class="card text-white bg-dark mb-3">
                <div class="card-header">-</div>
                <div class="card-body card-info">
                </div>
            </div>

        <div class="card text-white bg-dark mb-3">
                <div class="card-header">-</div>
                <div class="card-body card-info">
                </div>
            </div>

        <div class="card text-white bg-info mb-3">
                <div class="card-header">1</div>
                <div class="card-body card-info">
                    <h4>today, get in the line!</h4>
                    <button class="btn btn-primary btn-sm">get in line</button>
                </div>
            </div>

        <div class="card text-white bg-secondary mb-3">
                <div class="card-header">2</div>
                <div class="card-body card-info">
                    <h4>get in the line!</h4>
                    <button class="btn btn-primary btn-sm">get in line</button>
                </div>
            </div>

    
        <div class="card text-white bg-warning mb-3">
                <div class="card-header">3</div>
                <div class="card-body card-info">
                    <h4>requested, waiting for response...</h4>
                    <button class="btn btn-danger btn-sm">cancel request</button>
                </div>
            </div>

        <div class="card text-white bg-danger mb-3">
                <div class="card-header">4</div>
                <div class="card-body card-info">
                    <h4> request rejected </h4>
                </div>
            </div>

        <div class="card text-white bg-success mb-3">
                <div class="card-header">5</div>
                <div class="card-body card-info">
                    <h4> the day is yours! </h4>
                </div>
            </div>

        <div class="card text-white bg-primary mb-3">
                <div class="card-header">6</div>
                <div class="card-body card-info">
                    <h4> room 8797 has taken the key </h4>
                </div>
            </div>
    
        <div class="card text-white bg-secondary mb-3">
                <div class="card-header">7</div>
                <div class="card-body card-info">
                    <h4>get in the line!</h4>
                    <button class="btn btn-primary btn-sm">get in line</button>
                </div>
            </div>

        <div class="card text-white bg-secondary mb-3">
                <div class="card-header">8</div>
                <div class="card-body card-info">
                    <h4>get in the line!</h4>
                    <button class="btn btn-primary btn-sm">get in line</button>
                </div>
            </div>

        <div class="card text-white bg-secondary mb-3">
                <div class="card-header">9</div>
                <div class="card-body card-info">
                    <h4>get in the line!</h4>
                    <button class="btn btn-primary btn-sm">get in line</button>
                </div>
            </div>

        <div class="card text-white bg-secondary mb-3">
                <div class="card-header">10</div>
                <div class="card-body card-info">
                    <h4>get in the line!</h4>
                    <button class="btn btn-primary btn-sm">get in line</button>
                </div>
            </div>

        <div class="card text-white bg-secondary mb-3">
                <div class="card-header">11</div>
                <div class="card-body card-info">
                    <h4>get in the line!</h4>
                    <button class="btn btn-primary btn-sm">get in line</button>
                </div>
            </div>

        <div class="card text-white bg-secondary mb-3">
                <div class="card-header">12</div>
                <div class="card-body card-info">
                    <h4>get in the line!</h4>
                    <button class="btn btn-primary btn-sm">get in line</button>
                </div>
            </div>


        <div class="card text-white bg-secondary mb-3">
                <div class="card-header">13</div>
                <div class="card-body card-info">
                    <h4>get in the line!</h4>
                    <button class="btn btn-primary btn-sm">get in line</button>
                </div>
            </div>

        <div class="card text-white bg-secondary mb-3">
                <div class="card-header">14</div>
                <div class="card-body card-info">
                    <h4>get in the line!</h4>
                    <button class="btn btn-primary btn-sm">get in line</button>
                </div>
            </div>

    </div>
    <button class="btn btn-primary btn-lg btn-block">next month</button>
</div>
<script type="module" src="static/js/index.js"></script>
{% endblock %}

flaskapp/templates/not_signed_in.html
{% extends "base.html" %}
{% block title %}
    registration
{% endblock %}

{% block content %}
<div class="centred-box">
<h1>Oups...</h1>
<h2>Seems like you're not signed in.</h2>
<h2>You can't use this service if you are not signed in.</h2>
<h2>Choose any of these options:</h2>
<button class="btn btn-primary" onclick="location.href='{{ url_for('site.sign_in') }}'">sign in</button>
<button class="btn btn-primary" onclick="location.href='{{ url_for('site.registration') }}'">registration</button>
</div>
{% endblock %}

flaskapp/templates/registration.html
{% extends "base.html" %}
{% block title %}
    registration
{% endblock %}

{% block content %}
<form class="centred-box" action="{{ url_for('site.registration') }}" method="POST">
    {{ form.hidden_tag() }}
    <div class="reg-grid">
            <div class="form-group reg-grid-element">
                    <label>name</label>
                    {{ form.name(class="form-control", placeholder="what's your name?") }}
                    {% if form.name.erros %}
                        <ul>{% for error in form.name.erros %} <li>{{ error }}</li> {% endfor %}</ul>
                    {% endif %}
                    
                </div>
                <div class="form-group reg-grid-element">
                    <label>surname</label>
                    {{ form.surname(class="form-control", placeholder="what about your surname?") }}
                    {% if form.surname.erros %}
                        <ul>{% for error in form.surname.erros %} <li>{{ error }}</li> {% endfor %}</ul>
                    {% endif %}
                    
                </div>
                <div class="form-group reg-grid-element">
                    <label>e-mail</label>
                    {{ form.email(class="form-control", placeholder="your e-mail here") }}
                    {% if form.email.erros %}
                        <ul>{% for error in form.email.erros %} <li>{{ error }}</li> {% endfor %}</ul>
                    {% endif %}
                    
                </div>
                <div class="form-group reg-grid-element">
                    <label>password</label>
                    {{ form.password(class="form-control", placeholder="your super safe password") }}
                    {% if form.password.erros %}
                        <ul>{% for error in form.password.erros %} <li>{{ error }}</li> {% endfor %}</ul>
                    {% endif %}
                    
                </div>
                <div class="form-group reg-grid-element">
                    <label>confirm password</label>
                    {{ form.confirm_password(class="form-control", placeholder="repeat your awesome password!") }}
                    {% if form.confirm_password.erros %}
                        <ul>{% for error in form.confirm_password.erros %} <li>{{ error }}</li> {% endfor %}</ul>
                    {% endif %}
                    
                </div>
                <div class="form-group reg-grid-element">
                    <label>room index</label>
                    {{ form.room(class="form-control", placeholder="your room number") }}
                    {% if form.room.erros %}
                        <ul>{% for error in form.room.erros %} <li>{{ error }}</li> {% endfor %}</ul>
                    {% endif %}
                    
                </div>
    </div>
    <div class="form-group">
            <button type="submit" class="btn btn-success">create an account!</button>
            <button type="button" class="btn btn-primary" onclick="location.href='{{ url_for('site.sign_in') }}';">sign in</button>
        </div>
    
        {% with messages = get_flashed_messages(with_categories=true) %}
            {% if messages %}
                {% for category, message in messages %}
                    <div class="alert alert-{{ category }}" role="alert">
                        {{ message }}
                    </div>
                {% endfor %}
            
            {% endif %}
        {% endwith %}
</form>
{% endblock %}

flaskapp/templates/sign_in.html
{% extends "base.html" %}
{% block title %}
    sign in
{% endblock %}

{% block content %}
<form class="centred-box" action="{{ url_for('site.sign_in') }}" method="POST">
    {{ form.hidden_tag() }}
    <div class="reg-grid">
        <div class="form-group reg-grid-element">
            <label>e-mail</label>
            {{ form.email(class="form-control", placeholder="remember your e-mail?") }}
            {% if form.email.errors %}
                <ul>{% for error in form.email.errors %} <li>{{ error }}}</li> {% endfor %}</ul>
            {% endif %}
        </div>
        <div class="form-group reg-grid-element">
            <label>password</label>
            {{ form.password(class="form-control", placeholder="don't forget the password") }}
            {% if form.password.errors %}
                <ul>{% for error in form.password.errors %} <li>{{ error }}}</li> {% endfor %}</ul>
            {% endif %}
        </div>
    </div>
    <div class="form-group">
            <button type="submit" class="btn btn-success">sign in!!</button>
            <button type="button" class="btn btn-primary" onclick="location.href='{{ url_for('site.registration') }}';">I have no account</button>
            <button type="button" class="btn btn-primary" onclick="location.href='{{ url_for('site.change_password') }}';">I forgot my password</button>
        </div>
        
        {% with messages = get_flashed_messages(with_categories=true) %}
        {% if messages %}
            {% for category, message in messages %}
                <div class="alert alert-{{ category }}" role="alert">        
                    {{ message }}
                </div>
            {% endfor %}
            
        {% endif %}
        {% endwith %}
</form>
{% endblock %}